### ISSUE TITLE
Linking msvcrt into mingw programs is not supported.

### ISSUE THREAD

**Issue by mornfall** [batterseapower/ansi-terminal#2]
Since GHC is using mingw on windows, it is incorrect to also link msvcrt into the same executable. This in theory could cause problems for haskell programs as well, but it certainly breaks hsc2hs: if a program depends on ansi-terminal, using hsc2hs in such a program will make it unbuildable. The executables generated by hsc2hs will link msvcrt (due to ansi-terminal) and segfault on startup (since they are compiled with mingw and linking the mingw runtime). This makes darcs unbuildable on windows if you enable testing (i.e. we can't run tests due to this problem).

**Comment by batterseapower** [comment]
I can certainly see why this might cause problems.

My original justification for linking in msvcrt was that GHC's base library also caused it to be linked in. However, I see that that dependency was removed in the 6.10 release series.

It also turns out that the mingw C runtime provides the (rather non-standard) function _get_osfhandle function that I need, so I don't even need the MS runtime linked in.

The version ansi-terminal v0.5.5 ships with this dependency removed. Thanks for the report!

**Comment by mornfall** [comment]
Great, thanks! I'll bump the dependency. (I now have test-framework running on our windows buildslave with a kludged ansi-terminal; I'll update it to the released version RSN.)
